services:
  mostbox:
    image: ghcr.io/most-people/most-box:0.5.0
    container_name: mostbox
    network_mode: host
    restart: unless-stopped
    environment:
      HOME: /data
    volumes:
      - /vol1/docker/mostbox/home:/data
