/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Web3IndexRouteImport } from './routes/web3/index'
import { Route as PingIndexRouteImport } from './routes/ping/index'
import { Route as NoteIndexRouteImport } from './routes/note/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Web3ToolsIndexRouteImport } from './routes/web3/tools/index'
import { Route as Web3Ed25519IndexRouteImport } from './routes/web3/ed25519/index'
import { Route as GameZhajinhuaIndexRouteImport } from './routes/game/zhajinhua/index'
import { Route as GameGandengyanIndexRouteImport } from './routes/game/gandengyan/index'
import { Route as ChatJoinIndexRouteImport } from './routes/chat/join/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Web3IndexRoute = Web3IndexRouteImport.update({
  id: '/web3/',
  path: '/web3/',
  getParentRoute: () => rootRouteImport,
} as any)
const PingIndexRoute = PingIndexRouteImport.update({
  id: '/ping/',
  path: '/ping/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const Web3ToolsIndexRoute = Web3ToolsIndexRouteImport.update({
  id: '/web3/tools/',
  path: '/web3/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const Web3Ed25519IndexRoute = Web3Ed25519IndexRouteImport.update({
  id: '/web3/ed25519/',
  path: '/web3/ed25519/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameZhajinhuaIndexRoute = GameZhajinhuaIndexRouteImport.update({
  id: '/game/zhajinhua/',
  path: '/game/zhajinhua/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGandengyanIndexRoute = GameGandengyanIndexRouteImport.update({
  id: '/game/gandengyan/',
  path: '/game/gandengyan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatJoinIndexRoute = ChatJoinIndexRouteImport.update({
  id: '/chat/join/',
  path: '/chat/join/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/game/': typeof GameIndexRoute
  '/note/': typeof NoteIndexRoute
  '/ping/': typeof PingIndexRoute
  '/web3/': typeof Web3IndexRoute
  '/chat/join/': typeof ChatJoinIndexRoute
  '/game/gandengyan/': typeof GameGandengyanIndexRoute
  '/game/zhajinhua/': typeof GameZhajinhuaIndexRoute
  '/web3/ed25519/': typeof Web3Ed25519IndexRoute
  '/web3/tools/': typeof Web3ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/chat': typeof ChatIndexRoute
  '/demo': typeof DemoIndexRoute
  '/download': typeof DownloadIndexRoute
  '/game': typeof GameIndexRoute
  '/note': typeof NoteIndexRoute
  '/ping': typeof PingIndexRoute
  '/web3': typeof Web3IndexRoute
  '/chat/join': typeof ChatJoinIndexRoute
  '/game/gandengyan': typeof GameGandengyanIndexRoute
  '/game/zhajinhua': typeof GameZhajinhuaIndexRoute
  '/web3/ed25519': typeof Web3Ed25519IndexRoute
  '/web3/tools': typeof Web3ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/game/': typeof GameIndexRoute
  '/note/': typeof NoteIndexRoute
  '/ping/': typeof PingIndexRoute
  '/web3/': typeof Web3IndexRoute
  '/chat/join/': typeof ChatJoinIndexRoute
  '/game/gandengyan/': typeof GameGandengyanIndexRoute
  '/game/zhajinhua/': typeof GameZhajinhuaIndexRoute
  '/web3/ed25519/': typeof Web3Ed25519IndexRoute
  '/web3/tools/': typeof Web3ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/app/'
    | '/chat/'
    | '/demo/'
    | '/download/'
    | '/game/'
    | '/note/'
    | '/ping/'
    | '/web3/'
    | '/chat/join/'
    | '/game/gandengyan/'
    | '/game/zhajinhua/'
    | '/web3/ed25519/'
    | '/web3/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/chat'
    | '/demo'
    | '/download'
    | '/game'
    | '/note'
    | '/ping'
    | '/web3'
    | '/chat/join'
    | '/game/gandengyan'
    | '/game/zhajinhua'
    | '/web3/ed25519'
    | '/web3/tools'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/app/'
    | '/chat/'
    | '/demo/'
    | '/download/'
    | '/game/'
    | '/note/'
    | '/ping/'
    | '/web3/'
    | '/chat/join/'
    | '/game/gandengyan/'
    | '/game/zhajinhua/'
    | '/web3/ed25519/'
    | '/web3/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  GameIndexRoute: typeof GameIndexRoute
  NoteIndexRoute: typeof NoteIndexRoute
  PingIndexRoute: typeof PingIndexRoute
  Web3IndexRoute: typeof Web3IndexRoute
  ChatJoinIndexRoute: typeof ChatJoinIndexRoute
  GameGandengyanIndexRoute: typeof GameGandengyanIndexRoute
  GameZhajinhuaIndexRoute: typeof GameZhajinhuaIndexRoute
  Web3Ed25519IndexRoute: typeof Web3Ed25519IndexRoute
  Web3ToolsIndexRoute: typeof Web3ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3/': {
      id: '/web3/'
      path: '/web3'
      fullPath: '/web3/'
      preLoaderRoute: typeof Web3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping/': {
      id: '/ping/'
      path: '/ping'
      fullPath: '/ping/'
      preLoaderRoute: typeof PingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3/tools/': {
      id: '/web3/tools/'
      path: '/web3/tools'
      fullPath: '/web3/tools/'
      preLoaderRoute: typeof Web3ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3/ed25519/': {
      id: '/web3/ed25519/'
      path: '/web3/ed25519'
      fullPath: '/web3/ed25519/'
      preLoaderRoute: typeof Web3Ed25519IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/zhajinhua/': {
      id: '/game/zhajinhua/'
      path: '/game/zhajinhua'
      fullPath: '/game/zhajinhua/'
      preLoaderRoute: typeof GameZhajinhuaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/gandengyan/': {
      id: '/game/gandengyan/'
      path: '/game/gandengyan'
      fullPath: '/game/gandengyan/'
      preLoaderRoute: typeof GameGandengyanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/join/': {
      id: '/chat/join/'
      path: '/chat/join'
      fullPath: '/chat/join/'
      preLoaderRoute: typeof ChatJoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  GameIndexRoute: GameIndexRoute,
  NoteIndexRoute: NoteIndexRoute,
  PingIndexRoute: PingIndexRoute,
  Web3IndexRoute: Web3IndexRoute,
  ChatJoinIndexRoute: ChatJoinIndexRoute,
  GameGandengyanIndexRoute: GameGandengyanIndexRoute,
  GameZhajinhuaIndexRoute: GameZhajinhuaIndexRoute,
  Web3Ed25519IndexRoute: Web3Ed25519IndexRoute,
  Web3ToolsIndexRoute: Web3ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
