/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Web3IndexRouteImport } from './routes/web3/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PingIndexRouteImport } from './routes/ping/index'
import { Route as NoteIndexRouteImport } from './routes/note/index'
import { Route as GameIndexRouteImport } from './routes/game/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as GameZhajinhuaIndexRouteImport } from './routes/game/zhajinhua/index'
import { Route as GameGandengyanIndexRouteImport } from './routes/game/gandengyan/index'
import { Route as CidCidIndexRouteImport } from './routes/cid/$cid/index'
import { Route as ChatJoinIndexRouteImport } from './routes/chat/join/index'
import { Route as ChatJoinDemoIndexRouteImport } from './routes/chat/join/demo/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const Web3IndexRoute = Web3IndexRouteImport.update({
  id: '/web3/',
  path: '/web3/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/web3/index.lazy').then((d) => d.Route))
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profile/index.lazy').then((d) => d.Route))
const PingIndexRoute = PingIndexRouteImport.update({
  id: '/ping/',
  path: '/ping/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ping/index.lazy').then((d) => d.Route))
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/note/index.lazy').then((d) => d.Route))
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/game/',
  path: '/game/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/download/index.lazy').then((d) => d.Route),
)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/chat/index.lazy').then((d) => d.Route))
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))
const GameZhajinhuaIndexRoute = GameZhajinhuaIndexRouteImport.update({
  id: '/game/zhajinhua/',
  path: '/game/zhajinhua/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/game/zhajinhua/index.lazy').then((d) => d.Route),
)
const GameGandengyanIndexRoute = GameGandengyanIndexRouteImport.update({
  id: '/game/gandengyan/',
  path: '/game/gandengyan/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/game/gandengyan/index.lazy').then((d) => d.Route),
)
const CidCidIndexRoute = CidCidIndexRouteImport.update({
  id: '/cid/$cid/',
  path: '/cid/$cid/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/cid/$cid/index.lazy').then((d) => d.Route),
)
const ChatJoinIndexRoute = ChatJoinIndexRouteImport.update({
  id: '/chat/join/',
  path: '/chat/join/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chat/join/index.lazy').then((d) => d.Route),
)
const ChatJoinDemoIndexRoute = ChatJoinDemoIndexRouteImport.update({
  id: '/chat/join/demo/',
  path: '/chat/join/demo/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/chat/join/demo/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/game/': typeof GameIndexRoute
  '/note/': typeof NoteIndexRoute
  '/ping/': typeof PingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/web3/': typeof Web3IndexRoute
  '/chat/join/': typeof ChatJoinIndexRoute
  '/cid/$cid/': typeof CidCidIndexRoute
  '/game/gandengyan/': typeof GameGandengyanIndexRoute
  '/game/zhajinhua/': typeof GameZhajinhuaIndexRoute
  '/chat/join/demo/': typeof ChatJoinDemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/chat': typeof ChatIndexRoute
  '/download': typeof DownloadIndexRoute
  '/game': typeof GameIndexRoute
  '/note': typeof NoteIndexRoute
  '/ping': typeof PingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/web3': typeof Web3IndexRoute
  '/chat/join': typeof ChatJoinIndexRoute
  '/cid/$cid': typeof CidCidIndexRoute
  '/game/gandengyan': typeof GameGandengyanIndexRoute
  '/game/zhajinhua': typeof GameZhajinhuaIndexRoute
  '/chat/join/demo': typeof ChatJoinDemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/download/': typeof DownloadIndexRoute
  '/game/': typeof GameIndexRoute
  '/note/': typeof NoteIndexRoute
  '/ping/': typeof PingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/web3/': typeof Web3IndexRoute
  '/chat/join/': typeof ChatJoinIndexRoute
  '/cid/$cid/': typeof CidCidIndexRoute
  '/game/gandengyan/': typeof GameGandengyanIndexRoute
  '/game/zhajinhua/': typeof GameZhajinhuaIndexRoute
  '/chat/join/demo/': typeof ChatJoinDemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/admin/'
    | '/app/'
    | '/chat/'
    | '/download/'
    | '/game/'
    | '/note/'
    | '/ping/'
    | '/profile/'
    | '/web3/'
    | '/chat/join/'
    | '/cid/$cid/'
    | '/game/gandengyan/'
    | '/game/zhajinhua/'
    | '/chat/join/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/chat'
    | '/download'
    | '/game'
    | '/note'
    | '/ping'
    | '/profile'
    | '/web3'
    | '/chat/join'
    | '/cid/$cid'
    | '/game/gandengyan'
    | '/game/zhajinhua'
    | '/chat/join/demo'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/admin/'
    | '/app/'
    | '/chat/'
    | '/download/'
    | '/game/'
    | '/note/'
    | '/ping/'
    | '/profile/'
    | '/web3/'
    | '/chat/join/'
    | '/cid/$cid/'
    | '/game/gandengyan/'
    | '/game/zhajinhua/'
    | '/chat/join/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  GameIndexRoute: typeof GameIndexRoute
  NoteIndexRoute: typeof NoteIndexRoute
  PingIndexRoute: typeof PingIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  Web3IndexRoute: typeof Web3IndexRoute
  ChatJoinIndexRoute: typeof ChatJoinIndexRoute
  CidCidIndexRoute: typeof CidCidIndexRoute
  GameGandengyanIndexRoute: typeof GameGandengyanIndexRoute
  GameZhajinhuaIndexRoute: typeof GameZhajinhuaIndexRoute
  ChatJoinDemoIndexRoute: typeof ChatJoinDemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web3/': {
      id: '/web3/'
      path: '/web3'
      fullPath: '/web3/'
      preLoaderRoute: typeof Web3IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping/': {
      id: '/ping/'
      path: '/ping'
      fullPath: '/ping/'
      preLoaderRoute: typeof PingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/game'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download/'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/zhajinhua/': {
      id: '/game/zhajinhua/'
      path: '/game/zhajinhua'
      fullPath: '/game/zhajinhua/'
      preLoaderRoute: typeof GameZhajinhuaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/gandengyan/': {
      id: '/game/gandengyan/'
      path: '/game/gandengyan'
      fullPath: '/game/gandengyan/'
      preLoaderRoute: typeof GameGandengyanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cid/$cid/': {
      id: '/cid/$cid/'
      path: '/cid/$cid'
      fullPath: '/cid/$cid/'
      preLoaderRoute: typeof CidCidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/join/': {
      id: '/chat/join/'
      path: '/chat/join'
      fullPath: '/chat/join/'
      preLoaderRoute: typeof ChatJoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/join/demo/': {
      id: '/chat/join/demo/'
      path: '/chat/join/demo'
      fullPath: '/chat/join/demo/'
      preLoaderRoute: typeof ChatJoinDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  GameIndexRoute: GameIndexRoute,
  NoteIndexRoute: NoteIndexRoute,
  PingIndexRoute: PingIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  Web3IndexRoute: Web3IndexRoute,
  ChatJoinIndexRoute: ChatJoinIndexRoute,
  CidCidIndexRoute: CidCidIndexRoute,
  GameGandengyanIndexRoute: GameGandengyanIndexRoute,
  GameZhajinhuaIndexRoute: GameZhajinhuaIndexRoute,
  ChatJoinDemoIndexRoute: ChatJoinDemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
